# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

# Default database configuration
db.default.driver=com.mysql.cj.jdbc.Driver
db.default.url="jdbc:mysql://localhost/bootsverleih"
db.default.username=root
db.default.password="m*X92Cn+Qp"

database.dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 32
  }
  throughput = 1
}